name: Test `{{ cookiecutter.project_name }}` action
on:
  push:
    branches:
      - main

jobs:
  test-{{ cookiecutter.project_name }}:
    runs-on: [ 'ubuntu-latest' ]
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        id: test
        uses: ./
        with:
          name: test-*
      - name: Check
        run: |
          echo "${% raw %}{{ steps.test.outputs.result }}{% endraw %}"
          test "${% raw %}{{ steps.test.outputs.result }}{% endraw %}" = "[test-2,test-1]"
